# Generated by Django 4.0.6 on 2022-12-09 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(unique=True, verbose_name='Идентификатор пользователя')),
                ('name', models.TextField(default='', verbose_name='Имя')),
                ('text', models.TextField(default='', verbose_name='Текст')),
                ('nsfw', models.BooleanField(verbose_name='Контент 18+')),
                ('last_activity', models.DateTimeField(null=True, verbose_name='Дата последней активности')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.TextField(default='', verbose_name='Идентификатор изображения')),
                ('image_url', models.TextField(default='', verbose_name='ссылка на оригинал изображения')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile', verbose_name='Профиль владельца')),
            ],
        ),
    ]
