# Generated by Django 4.0.6 on 2022-12-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_image_options_interaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together={('initiator', 'subject')},
        ),
    ]
