# Generated by Django 4.0.6 on 2022-12-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_profile_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nsfw',
            field=models.BooleanField(default=False, verbose_name='Контент 18+'),
        ),
    ]
